[package]
name = "my_bevy_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
wasm-bindgen = "0.2.78"

[dev-dependencies]
trunk = "*"

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = 3
