[package]
name = "my_bevy_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_ecs_tilemap = "0.14.0"
iyes_perf_ui = "0.3.0"
rand = "0.8.5"
wasm-bindgen = "0.2.78"

[dependencies.web-sys]
version = "0.3.70"
features = ["console"]

[dev-dependencies]
trunk = "*"

[profile.dev]
opt-level = "z"
# data-wasm-opt = "0"

[profile.release]
opt-level = "z"
# https://bevy-cheatbook.github.io/platforms/wasm/size-opt.html
lto = "thin"
