[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy-inspector-egui = "0.27.0"
iyes_perf_ui = "0.3.0"
bevy = "0.14.2"

[dependencies.bevy_rapier2d]
version = "0.27.0"
features = ["debug-render-2d"]

[profile.dev.package.bevy_rapier2d]
opt-level = 3
