[package]
name = "my_bevy_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs_ldtk = "0.10.0"
bevy_ecs_tilemap = "0.14.0"
iyes_perf_ui = "0.3.0"
rand = "0.8.5"
serde = "1.0.210"
serde_json = "1.0.128"
wasm-bindgen = "0.2.78"

[dependencies.bevy]
version = "0.14.2"
# Disable the default features if there are any that you do not want
default-features = false
# https://docs.rs/crate/bevy/latest/features
features = [
    # "android_shared_stdcxx",
    "animation",
    "bevy_asset",
    "bevy_audio",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    # "bevy_gizmos",
    # "bevy_gltf",
    # "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "default_font",
    # "hdr",
    # "multi_threaded",
    "png",
    # "smaa_luts",
    "sysinfo_plugin",
    # "tonemapping_luts",
    "vorbis",
    "webgl2",
    # "x11",
]

[dependencies.web-sys]
version = "0.3.70"
features = ["console", "Window", "Storage"]

[dependencies.bevy_rapier2d]
version = "0.27.0"
features = ["debug-render-2d"]


[dev-dependencies]
trunk = "*"

[profile.dev]
opt-level = "z"
# data-wasm-opt = "0"

# https://rapier.rs/docs/user_guides/bevy_plugin/common_mistakes#my-local-build-of-rapier-is-slower-than-the-online-demos
[profile.dev.package.bevy_rapier2d]
opt-level = 3


[profile.release]
opt-level = "z"
# https://bevy-cheatbook.github.io/platforms/wasm/size-opt.html
lto = "thin"
