[build]
# target = "wasm32-unknown-unknown"

# rustflags = ["--cfg=web_sys_unstable_apis", "-C"]

# bevy_rapier2dが依存しているbevy_eguiがweb_sysのunstable API (bevy_egui::manage_clipboard) を使っているため、
# 以下のオプションが必要
rustflags = ["--cfg=web_sys_unstable_apis"]

# https://github.com/mozilla/sccache
# rustc-wrapper = "sccache.exe"
