# https://github.com/bevyengine/bevy_github_ci_template/blob/main/.github/workflows/release.yaml

name: Release

on:
  push:
    branches: ["main"]

env:
  use_git_lfs: false
  binary: magiaforge

jobs:
  # Build for wasm
  release-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: install trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build

      - name: add CNAME
        run: echo "magiaforge.app" > ./docs/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  # Build for Windows
  release-windows:
    runs-on: windows-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Prepare package
        run: |
          mkdir windows
          cp target/x86_64-pc-windows-msvc/release/${{ env.binary }}.exe windows/

      - name: Package as a zip
        run: |
          Compress-Archive -Path windows/* -DestinationPath ${{ env.binary }}.zip

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.binary }}.zip
          name: windows
          retention-days: 1

      - name: Get current date on Windows
        run: |
          echo "datetime=$(powershell -Command "(Get-Date).ToString('yyyy-MM-dd')")" >> $env:GITHUB_ENV

      # リポジトリの Settings > Actions > General > Workflow permissions を
      # Read and write permissions に変更する必要がある
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.binary }}.zip
          asset_name: ${{ env.binary }}-windows-${{ env.datetime }}.zip
          tag: ${{ env.datetime }}
          overwrite: true
          prerelease: true
