# https://github.com/bevyengine/bevy_github_ci_template/blob/main/.github/workflows/release.yaml

name: Release

on:
  push:
    branches: ["main"]

env:
  use_git_lfs: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: install trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
